function config = create_default_pipeline()
%CREATE_DEFAULT_PIPELINE

  config = feature_calculator.create(...
    'normal_pose_calculator', {}, ...
    'rgb_calculator', {'Input', 'normal_image'}, ...
    'lab_calculator', {'Input', 'rgb'}, ...
    'mr8_calculator', {'Input', 'rgb'}, ...
    'boundary_mask_calculator', {'InputImage', 'rgb'}, ...
    'dense_hog_calculator', {'Input', 'rgb'}, ...
    'pose_map_calculator', {...
      'InputImage', 'rgb', ...
      'InputPose', 'normal_pose' ...
    }, ...
    'clothing_detector', {...
      'Input', {...
        'rgb', ...
        'lab', ...
        'mr8', ...
        'boundary_mask', ...
        'dense_hog',...
        'pose_map' ...
        }, ...
      'InputAnnotation', 'normal_skinhair_annotation',...
      'Labels', {'null', 'skin', 'hair', 'any'},...
      'Output', 'skinhair_map'...
    }, ...
    'style_descriptor2', {...
      'Input', {...
        'rgb', ...
        'lab', ...
        'mr8', ...
        'boundary_mask', ...
        'dense_hog', ...
        'skinhair_map'...
        }, ...
      'Output', 'style_descriptor2'...
    });

end

