function config = create(varargin)
%CREATE Create a new calculator configuration.

  config = struct( ...
    'name', 'style_descriptor2', ...
    'input', {{...
      'rgb', ...
      'lab', ...
      'mr8', ...
      'gradients', ...
      'boundary_mask', ...
      'dense_hog', ...
      'skinhair_map'...
      }}, ...
    'input_pose', 'normal_pose', ...
    ...'output_raw_descriptor', 'raw_descriptor', ...
    'output', 'style_descriptor2', ...
    'patch_size', [32, 32], ...
    'grid_size',  [4, 4], ...
    'quantizer',  [], ...
    'reducer',   [] ...
  );
  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'Input'
        config.input = varargin{i+1};
      case 'InputPose'
        config.input_pose = varargin{i+1};
      case 'Quantizer'
        config.quantizer = varargin{i+1};
      case 'Reducer'
        config.reducer = varargin{i+1};
    end
  end

end

