function output = PARSE_from_FASHIONISTA(input)
%PARSE_FROM_FASHIONISTA

  assert(isscalar(input));
  output.point = [...
      input.right_ankle_x,     input.right_ankle_y;...
      input.right_knee_x,      input.right_knee_y;...
      input.right_hip_x,       input.right_hip_y;...
      input.left_hip_x,        input.left_hip_y;...
      input.left_knee_x,       input.left_knee_y;...
      input.left_ankle_x,      input.left_ankle_y;...
      input.right_hand_x,      input.right_hand_y;...
      input.right_elbow_x,     input.right_elbow_y;...
      input.right_shoulder_x,  input.right_shoulder_y;...
      input.left_shoulder_x,   input.left_shoulder_y;...
      input.left_elbow_x,      input.left_elbow_y;...
      input.left_hand_x,       input.left_hand_y;...
      input.neck_x,            input.neck_y;...
      input.head_x,            input.head_y;...
      ];
  output.score = NaN;

end

