function config = create( varargin )
%CREATE Create a new calculator configuration.

  config = struct(...
    'name', 'labeling_extractor', ...
    'input', {{...
      'clothing_localization', ...
      'exemplar_localization', ...
      'rectified_localization', ...
      'combined_localization' ...
      }}, ...
      ... 'input_labels', {{...
      ... 'knn_predicted_labels', ...
      ... 'exemplar_labels', ...
      ... 'rectified_labels', ...
      ... 'combined_labels' ...
      ... }},...
    'output', {{...
      'global_appearance_labeling', ...
      'exemplar_appearance_labeling', ...
      'rectified_mask_labeling', ...
      'combined_labeling' ...
      }} ...
    );
  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'Input', config.input = varargin{i+1};
      case 'InputLabels', config.input = varargin{i+1};
      case 'Output', config.output = varargin{i+1};
    end
  end

end

