function config = create(varargin)
%CREATE Create a new calculator configuration.

  config = struct( ...
    'name', 'clothing_detector', ...
    'input', {{...
      'rgb', ...
      'lab', ...
      'mr8', ...
      'boundary_mask', ...
      'dense_hog', ...
      'pose_map' ...
      }}, ...
    'annotation', 'clothing_annotation', ...
    'labels', {{}}, ...
    'output', 'clothing_map', ...
    'classifier', [] ...
  );
  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'Input',           config.input = varargin{i+1};
      case 'InputAnnotation', config.annotation = varargin{i+1};
      case 'Output',          config.output = varargin{i+1};
      case 'Labels',          config.labels = varargin{i+1};
    end
  end

  if isempty(config.labels)
    warning('clothing_detector:create', 'Labels are empty.')
  end

end

