function value = sge_environment
%SGE_ENV Return a struct of sge environmental variables

  fields = {...
    'NSLOTS', @str2double;...
    'NHOSTS', @str2double;...
    'JOB_ID', @str2double;...
    'JOB_NAME', @char;...
    'REQUEST', @char;...
    'QUEUE', @char;...
    'SGE_TASK_ID', @str2double;...
    'SGE_TASK_FIRST', @str2double;...
    'SGE_TASK_LAST', @str2double;...
    'SGE_TASK_STEPSIZE', @str2double;...
    'SGE_ARCH', @char;...
  };
  value = struct;
  for i = 1:size(fields, 1)
    x = getenv(fields{i, 1});
    value.(lower(fields{i, 1})) = fields{i, 2}(x);
  end

end
