function config = create(varargin)
%CREATE Create a new calculator configuration.

  config = struct( ...
    'name', 'combined_localizer', ...
    'input', {{...
      'clothing_localization', ...
      'exemplar_localization', ...
      'softmask_transfer' ...
      }}, ...
    'input_labels', {{...
      'knn_predicted_labels', ...
      'exemplar_labels', ...
      'softmask_labels' ...
      }}, ...
    'annotation',        'clothing_annotation', ...
    'annotation_labels', 'clothing_labels', ...
    'output',            'combined_localization', ...
    'output_labels',     'combined_labels', ...
    'lambdas',           [] ... % Best [ 0.448934 0.278194 0.268954 ]
  );
  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'Input',           config.input = varargin{i+1};
      case 'InputLabels',     config.input_labels = varargin{i+1};
      case 'InputAnnotation', config.annotation = varargin{i+1};
      case 'InputAnnotationLabels', config.annotation_labels = varargin{i+1};
      case 'Output',          config.output = varargin{i+1};
      case 'OutputLabels',    config.output_labels = varargin{i+1};
    end
  end
  
  config.lambdas = ones(size(config.input)) / numel(config.input);

end

