function config = create(varargin)
%CREATE Create a new calculator configuration.

  DEFAULT_DB_FILE = 'data/paperdoll_exemplars.bdb';

  config = struct( ...
    'name',                        'softmask_transferer', ...
    'input',                       {{'rgb', 'lab', 'mr8', 'dense_hog'}}, ...
    'input_pose_map',              'pose_map', ...
    'input_image',                 'normal_image', ...
    'input_exemplar_ids',          'knn_retrieved_ids', ...
    'exemplar_localization',       'clothing_localization', ...
    'exemplar_labels',             'clothing_labels', ...
    'output',                      'softmask_transfer',...
    'output_labels',               'softmask_labels',...
    'output_segmentation',         'softmask_segmentation',...
    'output_segment_geometry',     'segment_geometry', ...
    'output_segment_bow',          'segment_bow', ...
    'output_segment_localization', 'segment_localization', ...
    'num_visual_words',            25, ...
    'pf_sigma_smooth',             0.3, ...
    'pf_k_threshold',              200, ...
    'pf_min_size',                 20, ...
    'num_matches',                 5, ...
    'num_exemplars',               25, ...
    'database_file',               DEFAULT_DB_FILE ...
  );

  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'Input'
        config.input = varargin{i+1};
      case 'InputImage'
        config.input_image = varargin{i+1};
      case 'DatabaseFile'
        config.database_file = varargin{i+1};
      case 'Output'
        config.output = varargin{i+1};
      case 'OutputSegmentation'
        config.output_segmentation = varargin{i+1};
      case 'NumVisualWords'
        config.num_visual_words = varargin{i+1};
    end
  end

end

