function config = create_default_pipeline(varargin)
%CREATE_DEFAULT_PIPELINE

  config = feature_calculator.create(...
    'normal_pose_calculator', {}, ...
    'pose_map_calculator', {'InputImage', 'normal_image'}, ...
    'rgb_calculator', {'Input', 'normal_image'}, ...
    'lab_calculator', {'Input', 'rgb'}, ...
    'mr8_calculator', {'Input', 'rgb'}, ...
    'dense_hog_calculator', {'Input', 'rgb'}, ...
    'softmask_transferer', varargin ...
    });

end

