function config = create(varargin)
%CREATE Create a new calculator configuration.

  % Localizer requires input_labels while detector doesn't.
  config = struct( ...
    'name', 'clothing_localizer', ...
    'input', {{...
      'rgb', ...
      'lab', ...
      'mr8', ...
      'boundary_mask', ...
      'dense_hog', ...
      'pose_map' ...
      }}, ...
    'input_labels', 'clothing_labels', ...
    'annotation', 'clothing_annotation', ...
    'labels', {{}}, ...
    'output', 'clothing_localization', ...
    'classifiers', [] ...
  );
  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'Input',           config.input = varargin{i+1};
      case 'InputLabels',     config.input_labels = varargin{i+1};
      case 'InputAnnotation', config.annotation = varargin{i+1};
      case 'Output',          config.output = varargin{i+1};
      case 'Labels',          config.labels = varargin{i+1};
    end
  end

  if isempty(config.labels)
    warning('clothing_localizer:create', 'Labels are empty.')
  end

end

