function config = create( varargin )
%CREATE Create a new calculator configuration.

  config = struct(...
    'name', 'labeling_evaluator', ...
    'annotation',        'clothing_annotation', ...
    'annotation_labels', 'clothing_labels', ...
    'input', {{...
        'cvpr2011_labeling', ...
        'global_labeling', ...
        'exemplar_labeling', ...
        'softmask_labeling', ...
        'combined_labeling', ...
        'refined_labeling'...
      }}, ...
    'input_labels', {{...
        'clothing_labels', ...
        'knn_predicted_labels', ...
        'exemplar_labels', ...
        'softmask_labels', ...
        'combined_labels', ...
        'refined_labels' ...
      }}, ...
    'output', {{...
        'cvpr2011_labeling', ...
        'global_labeling', ...
        'exemplar_labeling', ...
        'softmask_labeling', ...
        'combined_labeling', ...
        'refined_labeling'...
      }}, ...
    'output_evaluation', 'evaluation' ...
    );
  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'InputAnnotation'
        config.annotation = varargin{i+1};
      case 'InputAnnotationLabels'
        config.annotation_labels = varargin{i+1};
      case 'Input', config.input = varargin{i+1};
      case 'InputLabels', config.input_labels = varargin{i+1};
      case 'Output', config.output = varargin{i+1};
      case 'OutputEvaluation', config.output_evaluation = varargin{i+1};
    end
  end

end

