function config = create(varargin)
%CREATE Create a new calculator configuration.

  config = struct( ...
    'name',               'clothing_refiner2', ...
    'input_image',        'rgb', ...
    'input_features',     {{'rgb', 'lab', 'boundary_mask'}}, ...
    'input_localization', 'combined_localization', ...
    'input_labels',       'clothing_labels', ...
    'output',             'refined_labeling', ...
    'output_labels',      'refined_labels', ...
    'add_unknown_label',  false ...
  );
  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'InputImage',        config.input = varargin{i+1};
      case 'InputFeatures',     config.input_features = varargin{i+1};
      case 'InputLocalization', config.input_localization = varargin{i+1};
      case 'InputLabels',       config.input_labels = varargin{i+1};
      case 'Output',            config.output = varargin{i+1};
      case 'OutputLabels',      config.output_labels = varargin{i+1};
      case 'ClothingRefinerAddUnknown', config.add_unknown_label = varargin{i+1};
    end
  end

end

