function config = create(varargin)
%CREATE Create a new calculator configuration.

  DEFAULT_DB_FILE = 'data/paperdoll_exemplars.bdb';

  config = struct( ...
    'name',                   'exemplar_localizer2', ...
    'input_exemplar_ids',     'knn_retrieved_ids', ...
    'input_labels',           'knn_predicted_labels', ...
    'input',                  {{...
      'rgb', 'lab', 'mr8', 'boundary_mask', 'gradient', 'pose_map'...
      }}, ...
    'input_annotation',       'refined_labeling', ...
    'exemplar_features',      'exemplar_features', ...
    'exemplar_annotation',    'exemplar_annotation', ...
    'exemplar_labels',        'clothing_labels', ...
    'output_localization',    'exemplar_localization', ...
    'output_labels',          'exemplar_labels', ...
    'sampling_rate',          0.05, ...
    'sampling_alpha',         0.0, ...
    'training_options',       {{ ...
      'Solver', 'l2lr',...
      'NumFolds',   1, ...
      'CRange',     10.^(-1), ...
      'EpsRange', 10.^-2, ...
      'BetaRange',  -0.33, ...
      'FeatureOrder', 2,...
      'FeatureIndependent', true,...
      'Quiet',      true ...
    }}, ...
    'database_file',          DEFAULT_DB_FILE, ...
    'max_exemplars',          25 ...
  );

  for i = 1:2:numel(varargin)
    switch varargin{i}
      case 'Input',               config.input = varargin{i+1};
      case 'InputExemplarIds',    config.input_exemplar_ids = varargin{i+1};
      case 'InputLabels',         config.input_labels = varargin{i+1};
      case 'DatabaseFile',        config.database_file = varargin{i+1};
      case 'OutputLabeling',      config.output_labeling = varargin{i+1};
      case 'OutputLabels',        config.output_labels = varargin{i+1};
    end
  end

end
